// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5-4KFHndqU5lyH24qeJufeyNDhz_z7L0',
    appId: '1:176364093014:web:bb314b381026a5f42cc5f7',
    messagingSenderId: '176364093014',
    projectId: 'project-k4-e5f3c',
    authDomain: 'project-k4-e5f3c.firebaseapp.com',
    storageBucket: 'project-k4-e5f3c.firebasestorage.app',
    measurementId: 'G-DM6HN01EPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACUPaaewcpqDI9-LG9fRccmUAOQ7afR5o',
    appId: '1:176364093014:android:170de112d85feff52cc5f7',
    messagingSenderId: '176364093014',
    projectId: 'project-k4-e5f3c',
    storageBucket: 'project-k4-e5f3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlSgfl55wllvyUzn0dYlO9FED2Hy9rZMI',
    appId: '1:176364093014:ios:fefe0f9829c57dc72cc5f7',
    messagingSenderId: '176364093014',
    projectId: 'project-k4-e5f3c',
    storageBucket: 'project-k4-e5f3c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLatihan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlSgfl55wllvyUzn0dYlO9FED2Hy9rZMI',
    appId: '1:176364093014:ios:fefe0f9829c57dc72cc5f7',
    messagingSenderId: '176364093014',
    projectId: 'project-k4-e5f3c',
    storageBucket: 'project-k4-e5f3c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLatihan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5-4KFHndqU5lyH24qeJufeyNDhz_z7L0',
    appId: '1:176364093014:web:651881d082390a9a2cc5f7',
    messagingSenderId: '176364093014',
    projectId: 'project-k4-e5f3c',
    authDomain: 'project-k4-e5f3c.firebaseapp.com',
    storageBucket: 'project-k4-e5f3c.firebasestorage.app',
    measurementId: 'G-JY14L5K1PF',
  );
}
